### ISSUE TITLE
Coq 8.4 version with Ltac profiling

### ISSUE THREAD

**Issue by JasonGross** [coq/repo-coqs#1]
Any chance there can be an opam repo package for v8.4 patched with [this patch](http://www.ps.uni-saarland.de/~ttebbi/ltacprof/ltac-profiling-0.1.patch), which is [Tobias Tebbi's LtacProf - Profiling for Ltac](http://www.ps.uni-saarland.de/~ttebbi/ltacprof/)?

**Comment by clarus** [comment]
Yes, all Coq versions are welcomed since this is a repository intended for developers.

In OPAM there is a feature to make packages with patches: https://github.com/ocaml/opam/wiki/Packaging#patching-sources Else a link to a GitHub fork is fine.

**Comment by JasonGross** [comment]
I've followed the instructions [on my fork](https://github.com/JasonGross/repo-coqs/compare/coq:master...master), but am still trying to figure out how to test it...

**Comment by JasonGross** [comment]
Managed to figure out how to test it.
